apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftapp
  labels:
    app: giftapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftapp
  template:
    metadata:
      labels:
        app: giftapp
    spec:
      # Pod-level security context
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: icr

      containers:
        - name: giftapp-container
          image: us.icr.io/sn-labs-paulvantuyl/giftapp
          ports:
            - containerPort: 3060

          # Container-level security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: gift-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3060
      protocol: TCP
  selector:
    app: giftapp